[package]
name = "namada-sdk-starter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = { version = "0.2" }
async-trait = "0.1.51"
borsh = "0.9.0"
namada = { git = "https://github.com/anoma/namada", rev="be403f735f6ec660c929533f5e3d4037dcd05b41", default-features = false, features = ["abciplus", "namada-sdk"] }
tendermint-config = {git="https://github.com/heliaxdev/tendermint-rs.git", rev="4db3c5ea09fae4057008d22bf9e96bf541b55b35"}
tendermint-rpc = {git="https://github.com/heliaxdev/tendermint-rs.git", rev="4db3c5ea09fae4057008d22bf9e96bf541b55b35", features = ["http-client"], default-features = false}
tokio = {version = "1.26.0", features = ["rt-multi-thread"]}
masp_primitives = { git = "https://github.com/anoma/masp", rev = "bee40fc465f6afbd10558d12fe96eb1742eee45c", features = ["transparent-inputs"] }
masp_proofs = { git = "https://github.com/anoma/masp", rev = "bee40fc465f6afbd10558d12fe96eb1742eee45c", features = ["bundled-prover", "download-params"]}
rand = {version = "0.8", default-features = false}
rand_core = {version = "0.6", default-features = false}

[patch.crates-io]
# TODO temp patch for <https://github.com/near/borsh-rs/issues/82>, <https://github.com/near/borsh-rs/issues/84> and more tba.
borsh = {git = "https://github.com/heliaxdev/borsh-rs.git", rev = "cd5223e5103c4f139e0c54cf8259b7ec5ec4073a"}
borsh-derive = {git = "https://github.com/heliaxdev/borsh-rs.git", rev = "cd5223e5103c4f139e0c54cf8259b7ec5ec4073a"}
borsh-derive-internal = {git = "https://github.com/heliaxdev/borsh-rs.git", rev = "cd5223e5103c4f139e0c54cf8259b7ec5ec4073a"}
borsh-schema-derive-internal = {git = "https://github.com/heliaxdev/borsh-rs.git", rev = "cd5223e5103c4f139e0c54cf8259b7ec5ec4073a"}
# The following 3 crates patch a work-around for https://github.com/smol-rs/polling/issues/38 breaking namada tooling build with nightly 2022-05-20
polling = {git = "https://github.com/heliaxdev/polling.git", rev = "02a655775282879459a3460e2646b60c005bca2c"}
async-io = {git = "https://github.com/heliaxdev/async-io.git", rev = "9285dad39c9a37ecd0dbd498c5ce5b0e65b02489"}
#async-process = {git = "https://github.com/heliaxdev/async-process.git", rev = "e42c527e87d937da9e01aaeb563c0b948580dc89"}

# patched to a commit on the `eth-bridge-integration+consensus-timeout` branch of our fork
tendermint = {git="https://github.com/heliaxdev/tendermint-rs.git", rev="4db3c5ea09fae4057008d22bf9e96bf541b55b35"}
tendermint-config = {git="https://github.com/heliaxdev/tendermint-rs.git", rev="4db3c5ea09fae4057008d22bf9e96bf541b55b35"}
tendermint-proto = {git="https://github.com/heliaxdev/tendermint-rs.git", rev="4db3c5ea09fae4057008d22bf9e96bf541b55b35"}
tendermint-rpc = {git="https://github.com/heliaxdev/tendermint-rs.git", rev="4db3c5ea09fae4057008d22bf9e96bf541b55b35"}
tendermint-light-client-verifier = {git="https://github.com/heliaxdev/tendermint-rs.git", rev="4db3c5ea09fae4057008d22bf9e96bf541b55b35"}

# patched to match 
ibc = {git = "https://github.com/heliaxdev/cosmos-ibc-rs.git", rev = "2d7edc16412b60cabf78163fe24a6264e11f77a9"}
ibc-proto = {git = "https://github.com/heliaxdev/ibc-proto-rs.git", rev = "7e527b5b8c95d83351e93ceafc14ac853224283f"}

# patched to the yanked 1.2.0 until masp updates bitvec
funty = { git = "https://github.com/bitvecto-rs/funty/", rev = "7ef0d890fbcd8b3def1635ac1a877fc298488446" }
